<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_verified_userLink login akan dikirimkan_b2d9d3</name>
   <tag></tag>
   <elementGuidId>6a82e289-c969-42d0-9505-897a7426dad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-login-telegram-dialog/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.telegram-login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;verified_userLink login akan dikirimkan ke akun telegram andaSilahkan cek pesan &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cd45798-890a-4af5-9622-9c1510125068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>telegram-login</value>
      <webElementGuid>2f8f7852-132b-445d-8d90-3e5f16cfd15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>verified_userLink login akan dikirimkan ke akun telegram andaSilahkan cek pesan telegram dari Azzam Kita!</value>
      <webElementGuid>69e62ced-0a32-452c-835d-4fb6dd9997f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-login-telegram-dialog[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;shared-dialog&quot;]/div[@class=&quot;shared-dialog-content&quot;]/div[@class=&quot;telegram-login&quot;]</value>
      <webElementGuid>1a014f4b-5c53-42ae-bd75-a10ddddfad3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-login-telegram-dialog/div/div/div/div</value>
      <webElementGuid>6b356bbf-5bad-483f-9479-214a10fa33c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Berhasil'])[1]/following::div[2]</value>
      <webElementGuid>b6e0cf45-0586-423f-a7ed-741342d5db9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[11]</value>
      <webElementGuid>03e1d5b0-7edb-4a17-a9b9-abc27fe898be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::div[1]</value>
      <webElementGuid>1f9d79b5-56f5-4875-9bf3-bb233d49f704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-login-telegram-dialog/div/div/div/div</value>
      <webElementGuid>99c9d2ff-1ba2-42f6-a473-d58a95f20268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'verified_userLink login akan dikirimkan ke akun telegram andaSilahkan cek pesan telegram dari Azzam Kita!' or . = 'verified_userLink login akan dikirimkan ke akun telegram andaSilahkan cek pesan telegram dari Azzam Kita!')]</value>
      <webElementGuid>c40ace1d-5676-44ec-91af-10e3f9ae03ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
