<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>a75bde1f-dcd7-4992-9671-bbdaa25730e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-button.my-1.mx-1.ng-star-inserted > button.align-items-center.btn.btn-action.btn-height.btn-lg.btn-outline-secondary.d-flex.justify-content-center.px-3.rounded.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Edit&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e4be1477-45d9-4190-a9a2-a84dbe1d8786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-items-center btn btn-action btn-height btn-lg btn-outline-secondary d-flex justify-content-center px-3 rounded ng-star-inserted</value>
      <webElementGuid>203f847d-173d-4972-9fff-ec1daa85df65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>218f87cf-d1ce-483f-be0e-34e9366142c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-pos-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;navbar-container&quot;]/div[@class=&quot;navbar-sidenav-container sidenav-overflow&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;overflow-content&quot;]/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-pos-transaksi[@class=&quot;ng-star-inserted&quot;]/app-pos-penjualan-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-lg-8 col-md-12 col-sm-12&quot;]/div[@class=&quot;transaction-wrapper&quot;]/div[@class=&quot;transaction-container__left&quot;]/div[@class=&quot;d-lg-block d-md-none d-sm-none d-none&quot;]/div[@class=&quot;v2-transaction-container__left__button&quot;]/app-button[@class=&quot;my-1 mx-1 ng-star-inserted&quot;]/button[@class=&quot;align-items-center btn btn-action btn-height btn-lg btn-outline-secondary d-flex justify-content-center px-3 rounded ng-star-inserted&quot;]</value>
      <webElementGuid>4339a2c5-ee74-4cf7-819e-0978ff72cad3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type=''])[2]</value>
      <webElementGuid>06f52e39-0f03-4464-931e-91b7a695d65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp2.030.000'])[1]/following::button[2]</value>
      <webElementGuid>6c9e114f-6bfb-4498-a25c-d5c2bb0ae526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Tagihan'])[1]/following::button[2]</value>
      <webElementGuid>ba87d65f-474f-41f9-89cb-98d869b773f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice'])[2]/preceding::button[3]</value>
      <webElementGuid>f40f34e9-ad65-49e8-a412-55e5b643781c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metode Pembayaran'])[1]/preceding::button[5]</value>
      <webElementGuid>fd3e6abf-9f97-4154-ab3a-dba0d2e3231d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button[2]/button</value>
      <webElementGuid>f3efab9d-6758-4b31-8183-a11418330d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>717fbc5a-3d75-4fdc-bb48-96c22965d74e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
