<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Penjualan</name>
   <tag></tag>
   <elementGuidId>4073f79f-4126-49d5-b69c-3aa7246d16d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='POS'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.btn-home-menu.mat-raised-button.mat-button-base.mat-default.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Penjualan&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e046059-59d6-46a2-88c9-f21a00afc571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>02341b25-16aa-436f-9ffb-d6b2da326d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/pos/transaksi/penjualan</value>
      <webElementGuid>62161e88-920b-47d9-8300-8ba3d69fab47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator btn-home-menu mat-raised-button mat-button-base mat-default ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>8cdbe5d0-8f91-4330-b38b-32f1be5e5ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>064c2cd2-8bd2-4a89-813d-50bfa68f7598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penjualan</value>
      <webElementGuid>904915dc-fec5-404c-b8b4-56b8721de5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-home-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;navbar-container&quot;]/div[@class=&quot;overflow-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/app-welcome[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;home-center-screen&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xxl-6 col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12&quot;]/div[@class=&quot;home-card pos-card ng-star-inserted&quot;]/div[1]/button[@class=&quot;mat-focus-indicator btn-home-menu mat-raised-button mat-button-base mat-default ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>5ca31d91-63b7-4b29-b2c8-0c1c2b983e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POS'])[1]/following::button[1]</value>
      <webElementGuid>31f11914-b49b-4d3a-a196-55c1ea46de9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::button[1]</value>
      <webElementGuid>66a1b656-0729-4ef0-96da-c91b38685aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembelian'])[1]/preceding::button[1]</value>
      <webElementGuid>6cd3c29e-de23-422d-835d-5656b27de0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>7725805b-1656-419b-81a7-bdb59dc3e9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Penjualan' or . = 'Penjualan')]</value>
      <webElementGuid>5edb521b-5d99-4c26-b97b-2d9518098465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
