<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_hargaInput</name>
   <tag></tag>
   <elementGuidId>3cde2106-57a2-4f3c-b0ec-d24834b7aba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='hargaInput'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.flex-row > app-input-money > div > div.input-group.input-group-merge.ng-star-inserted > #hargaInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;0&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebf4431c-9226-42bd-810a-384d7ea4f02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70ad4e7b-16b4-4f59-b675-eb436be1b485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hargaInput</value>
      <webElementGuid>c01f5560-c79a-4185-a914-9b0dcb2d55a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ca789faf-0b9d-4092-b75f-2143847f77b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3c01d5e1-f9f9-413f-9f51-cc2781eedf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-pos-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;navbar-container&quot;]/div[@class=&quot;navbar-sidenav-container sidenav-overflow&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;overflow-content&quot;]/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-pos-transaksi[@class=&quot;ng-star-inserted&quot;]/app-pos-penjualan-edit[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;ps-xl-1 ps-lg-auto col-xl-9 col-lg-12 col-md-12 col-sm-12 col-12&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[1]/app-card[1]/div[@class=&quot;v2-card-custom mb-2&quot;]/div[@class=&quot;v2-card-custom__content&quot;]/div[@class=&quot;px-2&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex flex-column px-2 font-14&quot;]/div[@class=&quot;d-none d-sm-none d-md-none d-lg-block d-xl-block ng-star-inserted&quot;]/div[@class=&quot;row no-gutters border-bottom bg-daftar-produk py-2 gap-xl-2 gap-lg-1 gap-md-0 ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;p-xl-0 p-lg-0 p-md-auto pb-md-2 col-xl-2 col-lg-2 col-md-10&quot;]/div[@class=&quot;d-flex flex-column gap-1&quot;]/div[@class=&quot;d-flex flex-row&quot;]/app-input-money[1]/div[1]/div[@class=&quot;input-group input-group-merge ng-star-inserted&quot;]/input[@id=&quot;hargaInput&quot;]</value>
      <webElementGuid>a5bfce0f-00f3-4e10-935a-d1fec803e298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='hargaInput'])[2]</value>
      <webElementGuid>5b185e88-8bfb-47b5-8cc4-a8ce7de65ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/app-input-money/div/div/input</value>
      <webElementGuid>e53c98f6-d09f-47ca-b4ae-08169bc73f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'hargaInput' and @placeholder = '0']</value>
      <webElementGuid>8be9f28b-f604-42d8-a0de-399d6ab8b9e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
