<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subtotal_jumlah0</name>
   <tag></tag>
   <elementGuidId>f07af554-2dfc-4c85-90ec-5508b95404d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jumlah0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jumlah0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=spinbutton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97e5ac62-2c9a-427d-b09a-ad205b238d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7e73f077-3067-40c7-a87f-17a5aea8ad1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-star-inserted ng-touched is-invalid ng-dirty ng-invalid</value>
      <webElementGuid>bced2c76-c205-4c6f-9686-ce92fa541ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah0</value>
      <webElementGuid>6326a38e-e389-49f7-9d0e-eaeb6adf1daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah</value>
      <webElementGuid>559a3849-5114-404e-830d-c038f80500d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9289f9ed-898d-49b3-8736-9ebc627a4df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-pos-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;navbar-container&quot;]/div[@class=&quot;navbar-sidenav-container sidenav-overflow&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;overflow-content&quot;]/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-pos-transaksi[@class=&quot;ng-star-inserted&quot;]/app-pos-penjualan-edit[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-invalid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;ps-xl-1 ps-lg-auto col-xl-9 col-lg-12 col-md-12 col-sm-12 col-12&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[1]/app-card[1]/div[@class=&quot;v2-card-custom mb-2&quot;]/div[@class=&quot;v2-card-custom__content&quot;]/div[@class=&quot;px-2&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex flex-column px-2 font-14&quot;]/div[@class=&quot;d-none d-sm-none d-md-none d-lg-block d-xl-block ng-star-inserted&quot;]/div[@class=&quot;row no-gutters border-bottom bg-daftar-produk py-2 gap-xl-2 gap-lg-1 gap-md-0 ng-touched ng-dirty ng-invalid&quot;]/div[@class=&quot;p-xl-0 p-lg-0 p-md-auto pb-md-2 col-xl-1 col-lg-1 col-md-2&quot;]/app-input-form[1]/div[@class=&quot;form-group mb-cos&quot;]/div[@class=&quot;input-group input-group-merge ng-star-inserted&quot;]/input[@class=&quot;form-control ng-star-inserted ng-touched is-invalid ng-dirty ng-invalid&quot;]</value>
      <webElementGuid>cd8c7e8d-2ba5-4b54-8976-772ba71897db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jumlah0']</value>
      <webElementGuid>ed7bf51c-6bd6-436c-9b14-eb6ce529ee6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/app-input-form/div/div/input</value>
      <webElementGuid>42bf390d-05b1-4af3-8af6-374b44d4a27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'jumlah0' and @placeholder = 'Jumlah']</value>
      <webElementGuid>ba73f2cf-fe60-4098-b230-4f6be46b5ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
