<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Kembali</name>
   <tag></tag>
   <elementGuidId>a245f5a3-8093-4b2d-947d-bd6c74339aa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Jika Penjualan DIEDIT atau TOTAL berbeda dengan sebelumnya, maka Invoice akan DICANCEL'])[1]/following::p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.align-items-center.btn.btn-action.btn-height.btn-lg.btn-outline-secondary.d-flex.justify-content-center.px-3.rounded.ng-star-inserted > p.label-cos.border-none</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Kembali&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6d5c4de1-b983-4274-a4e9-e13b3df22531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-cos border-none</value>
      <webElementGuid>19531232-77b2-4a26-9b65-ded7df5de8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali</value>
      <webElementGuid>13e2fa9c-76a9-49b8-aa34-6615f0c119a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-pos-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;navbar-container&quot;]/div[@class=&quot;navbar-sidenav-container sidenav-overflow&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;overflow-content&quot;]/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-pos-transaksi[@class=&quot;ng-star-inserted&quot;]/app-pos-penjualan-edit[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;d-lg-block d-md-block d-sm-block d-none mt-lg-2 mt-md-2 mt-sm-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;d-flex flex-row float-right&quot;]/div[@class=&quot;d-flex flex-row gap-2&quot;]/app-button[1]/button[@class=&quot;align-items-center btn btn-action btn-height btn-lg btn-outline-secondary d-flex justify-content-center px-3 rounded ng-star-inserted&quot;]/p[@class=&quot;label-cos border-none&quot;]</value>
      <webElementGuid>49b3850e-1842-4614-881d-c8c4a9bca78e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jika Penjualan DIEDIT atau TOTAL berbeda dengan sebelumnya, maka Invoice akan DICANCEL'])[1]/following::p[1]</value>
      <webElementGuid>2053bbce-e338-46c1-bd80-53c4eb5e58c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimal Pembayaran'])[1]/following::p[2]</value>
      <webElementGuid>fef71f07-79be-4c9e-bd6b-03a0c98fe127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kembali']/parent::*</value>
      <webElementGuid>3028d314-8424-4b18-a276-4a6925fe2691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/app-button/button/p</value>
      <webElementGuid>f4cd58f4-c11c-4911-a1a2-017bf9c36e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Kembali' or . = 'Kembali')]</value>
      <webElementGuid>2e516eb0-93d9-4bf3-90ac-814c014bbdba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
